# Generated by Django 4.2.7 on 2025-10-05 17:01

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_email_confirmed_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture for the user",
                null=True,
                upload_to=apps.users.models.user_profile_picture_path,
            ),
        ),
    ]
